### PR TITLE
fixed order of i/j in lon/lat bnds figure

### PR DESCRIPTION
**Pull request by neumannd**
* updated/corrected order of indices i/j in Fig 2 (2D lon/lat bounds)
* updated/corrected order of indices i/j in caption of Fig 2
* renamed "figure 1" to "figure 3" in Appendix i
* updated history

See issue #295 for discussion of these changes.

### CODE REVIEW

**Comment by erget** [comment]
Hi @neumannd thanks for sending this! We're almost there. I'm roping in @AndersMS because he had a look late Friday and noticed a few issues that I'm quoting here:

> The change ... means that the vertices must be numbered clockwise, not anti-clockwise as in the updated figure.
> 
> "Bounds for 2-D coordinate variables with 4-sided cells In the case where the horizontal grid is described by two-dimensional auxiliary coordinate variables in latitude lat(n,m) and longitude lon(n,m), and the associated cells are four-sided, then the boundary variables are given in the form latbnd(n,m,4) and lonbnd(n,m,4), where the trailing index runs over the four vertices of the cells. Let us call the side of cell (j,i) facing cell (j,i-1) the "i-1" side, the side facing cell (j,i+1) the "i+1" side, and similarly for "j-1" and "j+1". Then we can refer to the vertex formed by sides i-1 and j-1 as (j-1,i-1). With this notation, the four vertices are indexed as follows: 0=(j-1,i-1), 1=(j-1,i+1), 2=(j+1,i+1), 3=(j+1,i-1).
> 
> If i-j-upward is a right-handed coordinate system (like lon-lat-upward), this ordering means the vertices will be traversed anticlockwise on the lon-lat surface seen from above. If i-j-upward is left-handed, they will be traversed clockwise on the lon-lat surface."
>
> Or alternatively, and probably a better match with the second paragraph of text, the lower right lat(j+1,i) lon(j+1,i) should read lat(j,i+1) lon(j,i+1) and the upper lat(j,i+1) lon(j,i+1) should read lat(j+1,i) lon(j+1,i).

Could you have one last pass over?

**Comment by neumannd** [comment]
@erget  @AndersMS : 

> Or alternatively, and probably a better match with the second paragraph of text, the lower right lat(j+1,i) lon(j+1,i) should read lat(j,i+1) lon(j,i+1) and the upper lat(j,i+1) lon(j,i+1) should read lat(j+1,i) lon(j+1,i).

Thanks for pointing it out. I will update the PR.

The R scripts, with which I generated the figures are provided here: https://github.com/neumannd/cell_bounds_figures_for_cf_conventions

**Comment by neumannd** [comment]
@erget Should we provide the URL mentioned above as reference of the figures in the CF Conventions? If I am not available in future, someone else could then easily get the R scripts and modify the figures. What do you think? Or would it blow up the CF Conventions reference list?

**Comment by AndersMS** [comment]
Hi Daniel @neumannd 
The updated figure (images/order_horizontal_bounds__2D_coord_variables.png) looks fine to me now!

**Comment by erget** [comment]
@neumannd I think it's a good idea to include the reference in the commit that introduces the figure, but not in the reference list, as it's more of a technical resource. We'll find it in the future if we do a blame on the file or the lines in the main document that reference it.

I'll merge this into my PR, rebasing your commits into a single one and including the reference to the R script. Once that's done the PR for CF Conventions master will be finalised so we can start the 3-week countdown to merge.

**Pull request closed without merging**
